### ISSUE TITLE
Could not verify token

### ISSUE THREAD

**Issue by s13t0ttz** [OpenScan-org/OpenScan2#40]
I input the token emailed to me. After a long delay a window pops up and says could not verify.

I tried the windows uploader too and it just stays loading.

**Comment by sokol07** [comment]
Have you tried it again later? Some time ago I had similar problem, I thought there is something wrong with my token but after a few hours it just worked at first try.

**Comment by s13t0ttz** [comment]
> @s13t0ttz I just released a new version of the uploader, could you try again with this one? [Uploader for OpenScanCloud.zip](https://github.com/OpenScanEu/OpenScanCloud/blob/main/uploader/OpenScanUploader.zip?raw=true)

Here's the log from the standalone.
[OpenScanUploader.log](https://github.com/OpenScanEu/OpenScan2/files/8882594/OpenScanUploader.log)

**Comment by s13t0ttz** [comment]
Hello! Have either of you had a chance to look at the log? 

I'd really like to get the scanner working fully.

**Comment by josepmy** [comment]
Hello @s13t0ttz I guess you exceed the max retries with your token.
`Max retries exceeded with url: /getTokenInfo?token=6X3153ae6a744326a5461adf4e784e78`

And then you get a timeout, did you double-check the settings and your token?

**Comment by s13t0ttz** [comment]
Hi Josepmy. Thanks for pointing that out. 

What settings would I double check? 

I reviewed the email I got from Thomas with the token and it is correct. 

This is the standalone uploader. There's no settings to adjust that I see.

**Comment by s13t0ttz** [comment]
Thomas? What do I do? Can you email me a new token?

**Comment by josepmy** [comment]
As I know, in my case using the python script to upload I must config the token inside the settings. 
Also check if you have any antivirus or some kind of app that could block the connection.

**Comment by josepmy** [comment]
@s13t0ttz I just test my script with your token and works perfectly sent the images and you should receive an email with the result of the scan. Please ignore the results they are test images.
This means that your token and the connection are ok, so the issue should be in your settings, check antivirus or block apps on your computer.

**Comment by s13t0ttz** [comment]
@josepmy - Thanks for doing that test! It is very helpful! 

Now that I think about it, I was separately trying to run Home Assistant on the RPI and I had trouble getting to the internet and what solved it was a command i input into the CLI. It was ipv4.ignore-auto-dns. Ater I did that, HomeAssistant ran like a charm. Unfortunately, I don't know what that means or how to solve that. 

I'm guessing something along this line. I can hit the Check for Updates button on the user interface and it works fine. Somehow just the token part isn't going through.

**Comment by s13t0ttz** [comment]
@josepmy - I have firewall turned off and no antivirus. What do you think about the ignore-auto-dns point? Is it possible there's some issue here?

**Comment by sokol07** [comment]
From what I see the issue looks like you couldn't communicate with the openscan server. What PC are you using, what OS? Do you have any non-standard security policies set up? What DNS servers do you use?
The error in log, the ignore-auto-dns information, fact that both built-it and standalone updater doesn't work make me think that there is some trouble resolving the openscanfeedback.dnsuser.de address by your PC. A quick check - can you ping this address? I've also tried requesting validation of your token (manually, with Postman) from the server and it seems to work fine, so the server side isn't an issue I think.

**Comment by sokol07** [comment]
I close the issue as this is not likely to be the OpenScan firmware or server-side issue. If the problem returns - we can reopen the issue.
