### ISSUE TITLE
Feature Request - Move to picamera2 --> much faster preview refresh rate, much faster routine

### ISSUE THREAD

**Issue by OpenScanEu** [OpenScan-org/OpenScan2#41]
After Pi foundation's move to libcamera, the older picamera python library no longer is supported. In short, this is the reason, why the preview-refresh time is above 2-4s instead of around 0.5-0.7s (full res with Pi Camera module v2)

I just checked back in and saw, that the new [picamera2 ](https://github.com/raspberrypi/picamera2) has been released as alpha and that it seems to work with Arducam modules as well. I started with a fresh Raspbian and installed both the Arducam drivers and the picamera2 library. It worked out of the box (standalone, without the current OpenScan firmware).

The main advantage of moving (back) to the python camera library is, that the preview refresh rate and the overall routine time could be improved to below 1s (even in full res, if the local network could handle it). I did some quick testing and get full res photos with the Arducam IMX519 within ~0.8s. Next advantage is, that the firmware code would get more consistent as the camera triggering for Arducam/PiCamera would be in the same module as the gphoto/Dslr triggering (see flask).

This should definitely be a goal for the next larger update.

**Comment by sokol07** [comment]
This sounds great - maybe this would be a good starting point to further features like the focus peaking we discussed earlier.
