### ISSUE TITLE
Feature Request --> Multi language support

### ISSUE THREAD

**Issue by OpenScanEu** [OpenScan-org/OpenScan2#42]
I have received this request many times. Even though English is considered the "standard" for many, increasing the accessibility by offering different firmware languages would be nice.

Though, I am not sure, whether this is doable with the current node-red implementation. Furthermore, maintenance might be another pita.... Hmmm, let's just keep the idea in mind

**Comment by sokol07** [comment]
There is no "fast" multilanguage support (like a lookup table with multiple languages and a language selector) in node-red, unfortunately. A walkaroud would be to make all texts dynamic and set them according to language setting... but this would definitely be a pita, both to implement and maintain...
