### ISSUE TITLE
Scanning disabled when only the external camera is connected. 

### ISSUE THREAD

**Issue by MichaelTimmermans** [OpenScan-org/OpenScan2#55]
I built the openscan classic and tried using the scanner with a DSLR only, so no other camera connected) 

When the camera is set to external this check -> ![image](https://user-images.githubusercontent.com/21260046/180651031-baaae4c0-9f92-4632-8b67-72f4c8479c71.png)

doesnt work. 

I commented out the check to make it work but that's not a solution obviously.

**Comment by OpenScanEu** [comment]
added a line to the "gphoto-node" shown above, which should fix this issue :)
