### ISSUE TITLE
Issue: Scanner Stopping/Freezing during scan

### ISSUE THREAD

**Issue by OpenScanFan** [OpenScan-org/OpenScan2#61]
Hi, I noticed since the latest update, the scanner now freezes during scanning (at random points in time), but not always, sometimes it manages to finish a scan

I do not change any settings in the settings tab, except for jpeg quality to 100% and rotary start and max angle at 30 degrees and min angle at 60 degrees

I'm using the mini with the IMX519

I flashed the SD, updated and restarted the process every time and no change
What could be the issue?

**Comment by OpenScanEu** [comment]
This sounds very weird and unfortunately I can not replicate the issue.
Maybe the jpeg quality=100 is overwhelming the memory?
Does it freeze in the default configuration too?
