### ISSUE TITLE
[Suggestion] Move inline python nodes to files

### ISSUE THREAD

**Issue by jorgerobles** [OpenScan-org/OpenScan2#67]
Trying to debug Openscan failures is hard (a nightmare), mainly due inline scripting.

Maybe using this extension makes a better way to edit, isolate and debug.
https://flows.nodered.org/node/node-red-contrib-pythonshell

**Comment by OpenScanEu** [comment]
See https://github.com/OpenScan-org/OpenScan3, this will be the basis for an overhaul of the existing, very messy back/frontend
