### ISSUE TITLE
Suggestion: Sliders - also allow numerical entry?

### ISSUE THREAD

**Issue by minimaker-nl** [OpenScan-org/OpenScan2#7]
Changing settings to a specific value can be hard using the sliders. A nice to have would be to be able to enter values instead of using the sliders.

**Comment by OpenScanEu** [comment]
This is possible, which sliders do you mean in particular?

**Comment by sokol07** [comment]
I agree, honestly saying - all of them. Motors setting and scan settings mainly but I believe that numerical input would be nice everywhere.
However, you can also set the precise value using arrows keys - when you click on a slider it doesn't show up but is is "selected" and clicking right and left arrow key you can change the value by 1 step (it's a little feature of NodeRed).

**Comment by minimaker-nl** [comment]
Nothing to add to sokol07's reply. Mainly scan and motor settings, but as an option it would be good for all places with sliders.

**Comment by mickmorrison** [comment]
This would be a useful addition, particularly in the scanning window — using the scanner from a tablet with touch screen the sliders are not easy to control. Arrows work provided you can select the setting you wish to change. It works its just prone to creating mistakes so using ‘tab’ to nav through fields allowing manual input would go a long way towards improving usability.
