### ISSUE TITLE
EXIF data

### ISSUE THREAD

**Issue by jope89** [OpenScan-org/OpenScan2#71]
Many apps like MESHROOM require camera data such as focal length and sensor size via embedded EXIF data in order to triangulate correctly.
The images sent by the scanner do not have EXIF

**Comment by DraycD** [comment]
had the same issue with MESHROOM

**Comment by OpenScanEu** [comment]
Meshroom is just showing a warning. The EXIF data is optional.
If meshroom can not reconstruct the image set, there is either a problem with the image quality (e.g. suface preparation of the object) or a settings issue in meshroom
