### ISSUE TITLE
Manual Focus doesn't work

### ISSUE THREAD

**Issue by AndreasEhrhard** [OpenScan-org/OpenScan2#72]
Disabeling the AUtofocus-Funktion of the adru-Cam doesn't work on Mini and also on Classic.
I changed the cameras, the Cable, the Raspberry Piy, ... 
What can I do?

**Comment by winne27** [comment]
The call to take a photo in the software uses wrong options. Soon I will provide a patcxh for that.

**Comment by apurvakalia** [comment]
One problem I found was the wrong access to the options dictionary ctrl in the file Arducam.py. It tries to access a key called "default" whereas the correct key value is "default_value". You can make that change manually in the code (I believe it is line 153 in Arducam.py)

**Comment by winne27** [comment]
Maybe this is the solution:

have a look to patch

https://github.com/OpenScan-org/OpenScan2/pull/75/files#diff-7572f6a8aafa0d7fce069e4ec04593fc585cebd3e72d421bd8eac40284ff5b35

or 

replace OpenScan.py by
 [update/mini/OpenScan.py](https://github.com/winne27/OpenScan2/blob/5082aac17edbef6a911509b5f9ad820d141dec78/update/mini/OpenScan.py)

**Comment by apurvakalia** [comment]
I tried the OpenScan.py mentioned above, but still running into problems:
- when using manual focus, I can see the camera focused in preview, but it reverts back to defocused mode again. I tried using stack option to enable to SET button but that does not help
- autofocus does not work at all. My object size is medium, but the camera keeps focusing on more distant objects
Any ideas?

**Comment by winne27** [comment]
Did you replace OpenScan.py in /usr/lib/python3/dist-packages/ ?

**Comment by AndreasEhrhard** [comment]
Hi!
I can#t work at the moment: Holliday on TEXEL.
Will try it, when I#m backmuome.

Regards
Andreas

Am 10.04.2023 um 18:43 schrieb Werner Schäffer ***@***.***>:

﻿

Did you replace OpenScan.py in /usr/lib/python3/dist-packages/ ?
