### ISSUE TITLE
Stepper motors are moving in one direction then an other.  

### ISSUE THREAD

**Issue by ccdanieldb** [OpenScan-org/OpenScan2#77]
Turntable and rotor steppers seem to move in random direction for each photo.  Changing to Turntable mode in (Advanced settings) seems to work just fine.  But scan seems to just be all over the place on each photo.

**Comment by OpenScanEu** [comment]
this is a feature not a bug ^^ The routine is somewhat optimized to equally space all the camera positions around the object.
