### ISSUE TITLE
Feature request: Disable Stepper Motors 

### ISSUE THREAD

**Issue by mrguybrush** [OpenScan-org/OpenScan2#85]
Hi!
First of all thank you for this great project. Is it possible to disable the Stepper motors while they are not in use? 
It cause unnecessary heat on the scanner and i want to have the possibility to rotate the item freely while the scan is not startet.
Thanks!

**Comment by OpenScanEu** [comment]
unfortunately, this is not possible with the current hardware. but we plan to release a new PCB solution as well as an improved hardware
